### ISSUE TITLE
Explore: updated names of parliaments

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/legislative-openness-data-explorer#14]
The updated spreadsheet includes the correct titles for each of the chambers in column P. Can these be added? 

https://docs.google.com/spreadsheets/d/1iABzv1hjXP0Ky9Jm_tggyfLzU_B0s0RiCy_nOkGBMAg/edit#gid=653281045

**Comment by michalskop** [comment]
merged to #21

**Comment by gregbrownm** [comment]
These all look good except for the Irish parliament. The name has some unique characters and the site isn't processing them. Can you trouble shoot?
