### ISSUE TITLE
Explore: colours

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/legislative-openness-data-explorer#16]
Can we make the grey color a bit lighter? Is there a palette of colors that I can choose from? Would be helpful to see this.

**Comment by michalskop** [comment]
We currently use this one: http://www.colourlovers.com/palette/949801/Traffic_Light

the grey may be easily chosen, for example from: http://www.w3schools.com/tags/ref_colorpicker.asp
(real grey is in the center + lighter/darker)

how about the 808080?

**Comment by gregbrownm** [comment]
I think even lighter for the grey. Lets try a6a6a6.

**Comment by gregbrownm** [comment]
Can we also change the Yellow? I prefer #ffff80 from here: http://www.w3schools.com/tags/ref_colorpicker.asp. 

Should be the last color change :)
