### ISSUE TITLE
Updating data

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/legislative-openness-data-explorer#21]
Prepare a way of updating the data
-> google spreadsheet
-> "update" page

**Comment by gregbrownm** [comment]
This one is a bit higher priority than the others -- I'd love to have a way to edit the data tables soon so I can finalize the information.

**Comment by michalskop** [comment]
Data may be updated in https://docs.google.com/spreadsheets/d/1iABzv1hjXP0Ky9Jm_tggyfLzU_B0s0RiCy_nOkGBMAg/edit#gid=653281045
but manual transfer to the server is so far required

**Comment by michalskop** [comment]
It is possible to update the data (parliaments and questions):
1. edit it at https://docs.google.com/spreadsheets/d/1iABzv1hjXP0Ky9Jm_tggyfLzU_B0s0RiCy_nOkGBMAg/edit#gid=653281045
2. visit http://beta.openparldata.org/update.php

**Comment by michalskop** [comment]
"Is information on parliament's contracts available?"

**Comment by michalskop** [comment]
@gregbrownm - It is necessary to change the name of the question in the 1st row and all the names of subquestion in 7th row (particularly the last occurrence of the subquestion)

**Comment by michalskop** [comment]
added info on files rights settings into readme

**Comment by gregbrownm** [comment]
I've update the data in the new spreadsheet (https://docs.google.com/spreadsheets/d/13ZfbbrUsl-ZwLdUWD9topnkrwCWSNOfPC2YIb0eWNc4/edit#gid=653281045) and am not seeing the changes reflected in the site. Any ideas on why this might be?

**Comment by michalskop** [comment]
@gregbrownm  Any example of the change, so I can test it?

**Comment by gregbrownm** [comment]
I reconciled all the instances where there were multiple entries for one chamber (Chile, Indonesia, Ireland, UK). If you need something more specific to test, let me know.

**Comment by michalskop** [comment]
@gregbrownm this was because of incorrect right settings of the generated (updated) data files (it was actually correctly described in README as "set all `.json` files in `inc/` files writable and readable by www server", but was not so at the server)
