### ISSUE TITLE
Coloring map with two houses

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/legislative-openness-data-explorer#24]
How to color the map (e.g., http://beta.openparldata.org/map/ ) if there are two houses in the country.
Any combination is possible (green+green = green, green+gray= ?, ...)

**Comment by gregbrownm** [comment]
Lets use this as the color scheme: 

green + green = green
green + grey = green
green + red = grey
grey + grey = grey
grey + red = red
red + red = red

**Comment by michalskop** [comment]
This seems to me a bit more logical, i.e., "show the better result and ignore grey"
green + green = green
green + yellow = green
green + red = green
green + grey = green
yellow + yellow = yellow
yellow + red = yellow
yellow  + grey = yellow 
red + red = red
red + grey = red
grey + grey = grey

**Comment by gregbrownm** [comment]
Lets go with this: 

green + green = green
green + yellow = green
green + red = yellow
green + grey = green
yellow + yellow = yellow
yellow + red = red
yellow + grey = yellow 
red + red = red
red + grey = red
grey + grey = grey
