### ISSUE TITLE
Download: Add data. 

### ISSUE THREAD

**Issue by gregbrownm** [KohoVolit/legislative-openness-data-explorer#32]
Add the data to the site so that the buttons on the download page work.

**Comment by michalskop** [comment]
"I've attached CSV and XLS documents to this email that should be used on the "Download" page. The current sheets that are downloaded include personal info about the folks who completed the survey, and we would like to keep that private. "

**Comment by michalskop** [comment]
Closed by 6fafba01a485df80cd63bb9eeacfdf8c7e80f8be
