### ISSUE TITLE
Data Collection: USA, Canada, Mexico

### ISSUE THREAD

**Issue by gregbrownm** [KohoVolit/legislative-openness-data-explorer#33]
Need to collect data from these countries before going live, if possible. Will make the landing map look much better.

(Also, FYI, adding some comments here for myself so I can track everything leading up to the launch in one place.)

**Comment by gregbrownm** [comment]
Other priority countries: India, Australia, Kenya, South Africa.

**Comment by michalskop** [comment]
They can be added to this spreadsheet:
https://docs.google.com/spreadsheets/d/1iABzv1hjXP0Ky9Jm_tggyfLzU_B0s0RiCy_nOkGBMAg/edit
(do not forget columns 992 and 993)
