### ISSUE TITLE
Refine the Data on Explore modal

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/legislative-openness-data-explorer#34]
Add a pre-filled google form to each chamber/question modal

**Comment by gregbrownm** [comment]
Add a button in the Explorer pop-ups that allow users to edit the data directly in the Explore page, rather than returning to the Contribute page.

Either a Google form that is generated with chamber and question, or a custom Google form for each question.

Michal to review possibilities.

**Comment by michalskop** [comment]
Note:
It is possible to pre-fill Google form using this:
https://support.google.com/docs/answer/160000?hl=en&rd=1
e.g.
https://docs.google.com/forms/d/12OtBmN05e8nym-y5PsyxwkC1k6Uv5dukWR1vlnxB5HY/viewform?entry.1286062036=Anything

**Comment by gregbrownm** [comment]
Awesome. Think you can throw a form together for this? We can simply use the form on the Contribute page, but add a section for question and chamber (which would be pre-filled based on the users selection).

**Comment by michalskop** [comment]
I just need from you:
a) add the field "Question?"
b) get the two field numbers for chamber and questions following https://support.google.com/docs/answer/160000?hl=en&rd=1

(Note: It would need the appropriate change in texts)

Also, I tried to embed the form, but it was not really working in the dialog, so I suggest to open in in new tab.

**Comment by michalskop** [comment]
"Google Form: things: I walked through the pre-fill instructions you sent, but not sure I was successful. Here's the link it generated. Think I missed something... Also, just made you an owner of the form (here) in case you can do this on your end."

**Comment by michalskop** [comment]
solved in texts
