### ISSUE TITLE
Fix "Suggest Edits" Button at Bottom of Explore Page

### ISSUE THREAD

**Issue by gregbrownm** [KohoVolit/legislative-openness-data-explorer#45]

**Comment by gregbrownm** [comment]
I might be missing something, but this button still doesn't work for me...

**Comment by michalskop** [comment]
Do we mean the same button? This one:
![screenshot from 2016-04-06 17 20 57](https://cloud.githubusercontent.com/assets/930251/14322113/fea7de9e-fc1b-11e5-8b38-4694107a2efa.png)
works for me ok:
![screenshot from 2016-04-06 17 21 50](https://cloud.githubusercontent.com/assets/930251/14322166/28a4bc8a-fc1c-11e5-83a6-9aa3480034a4.png)
(May be, try reloading?)
