### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by gregbrownm** [KohoVolit/legislative-openness-data-explorer#46]
When you click the colored icon for "Does the parliament provide plain language summaries of legislative information?" the subquestion reads: "Summaries are provided for". 

Can we change to: "Plain language summaries are provided for the following types of information"

**Comment by gregbrownm** [comment]
I want to link to the smaller surveys on the contribute page, but can't figure out how to add links (its a CSV file, so markdown, etc.) doesn't work. 

http://beta.openparldata.org/contribute/

**Comment by gregbrownm** [comment]
In question "Are committee reports available?" the answer for Argentina shows two "Not available" answers under one of the subquestions. I reviewed the data and can't figure out why... Same is true with Cameroon, Guatemala, and Macedonia. 

Also, subquestions are messed up. Questions on means (vd-vj) and formats (xn-xu) are combined into one question, rather than being separated.

**Comment by michalskop** [comment]
a) this is the kind of things you ma change in the google sheet (and than just run update.php) (I've changed this particular one)
c) it was a single problem (the same subquestion id for 2 different subquestions)

**Comment by michalskop** [comment]
b) yes, it is still possible, but it is necessary to use directly HTML 
e.g., 
"Let us <a href='http://ndi.org'>link to NDI</a>"
is written as 
`"Let us <a href='http://ndi.org'>link to NDI</a>"`

A bit more complicated, but still rather doable, IMHO (just be careful with the quotation marks, the inside ones should be different from the outside ones - as it is at the example above)

**Comment by gregbrownm** [comment]
All sounds good. Thanks!
