### ISSUE TITLE
Are parliamentary documents translated? 

### ISSUE THREAD

**Issue by gregbrownm** [KohoVolit/legislative-openness-data-explorer#49]

**Comment by michalskop** [comment]
@gregbrownm what do you mean?

**Comment by gregbrownm** [comment]
The scoring for this question is off. If the country doesn't have multiple languages (see column BE for answer to this question), it should say "Other" and be gray. It currently shows these countries as red. Can you fix?

**Comment by gregbrownm** [comment]
And if there are not multiple languages, the subquestion answer should just read N/A.
