### ISSUE TITLE
Footer: logos

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/legislative-openness-data-explorer#6]
Can we add logos in the footer? We should have NDI, KohoVolit, and the Legislative Openness Working Group logo (which I can send to you). Not sure exactly how this should be displayed, but would be great if you could throw something together and I can comment.

**Comment by gregbrownm** [comment]
Something like this might work well: http://openelectiondata.net/en/. I like the simplicity and including the navigation options. I'll send NDI's logo in an email.
